 # Importing Dependencies

In [133]:
import pandas as pd
import numpy as np
from sklearn.model_selection  import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier , GradientBoostingClassifier
from sklearn.metrics import classification_report

# Data Collection
1 True_news_dataset -- True_data
2 fake_news_dataset -- fake_data

In [45]:
true_data = pd.read_csv('/content/True (1).csv', engine='python', on_bad_lines='warn')

/tmp/ipykernel_326/3688312568.py:1: ParserWarning: Skipping line 2902: unexpected end of data

  true_data = pd.read_csv('/content/True (1).csv', engine='python', on_bad_lines='warn')

In [46]:
fake_data = pd.read_csv('/content/Fake (6).csv' , engine='python', on_bad_lines='warn')

/tmp/ipykernel_326/2823017780.py:1: ParserWarning: Skipping line 2389: unexpected end of data

  fake_data = pd.read_csv('/content/Fake (6).csv' , engine='python', on_bad_lines='warn')

# Data Preprocessing

In [47]:
true_data.head()

,title,text,subject,date
0,"As U.S. budget fight looms, Republicans flip t...",WASHINGTON (Reuters) - The head of a conservat...,politicsNews,"December 31, 2017"
1,U.S. military to accept transgender recruits o...,WASHINGTON (Reuters) - Transgender people will...,politicsNews,"December 29, 2017"
2,Senior U.S. Republican senator: 'Let Mr. Muell...,WASHINGTON (Reuters) - The special counsel inv...,politicsNews,"December 31, 2017"
3,FBI Russia probe helped by Australian diplomat...,WASHINGTON (Reuters) - Trump campaign adviser ...,politicsNews,"December 30, 2017"
4,Trump wants Postal Service to charge 'much mor...,SEATTLE/WASHINGTON (Reuters) - President Donal...,politicsNews,"December 29, 2017"

In [48]:
fake_data.head()

,title,text,subject,date
0,Donald Trump Sends Out Embarrassing New Year’...,Donald Trump just couldn t wish all Americans ...,News,"December 31, 2017"
1,Drunk Bragging Trump Staffer Started Russian ...,House Intelligence Committee Chairman Devin Nu...,News,"December 31, 2017"
2,Sheriff David Clarke Becomes An Internet Joke...,"On Friday, it was revealed that former Milwauk...",News,"December 30, 2017"
3,Trump Is So Obsessed He Even Has Obama’s Name...,"On Christmas day, Donald Trump announced that ...",News,"December 29, 2017"
4,Pope Francis Just Called Out Donald Trump Dur...,Pope Francis used his annual Christmas Day mes...,News,"December 25, 2017"

### Labeling data -- to include the target variable in the both true or fake data files

###True_data got label 1
###fake_data got label 0

In [49]:
#Labeling
true_data['label'] = 1
fake_data['label'] = 0

In [50]:
#Checking for Labeling
true_data.head()

,title,text,subject,date,label
0,"As U.S. budget fight looms, Republicans flip t...",WASHINGTON (Reuters) - The head of a conservat...,politicsNews,"December 31, 2017",1
1,U.S. military to accept transgender recruits o...,WASHINGTON (Reuters) - Transgender people will...,politicsNews,"December 29, 2017",1
2,Senior U.S. Republican senator: 'Let Mr. Muell...,WASHINGTON (Reuters) - The special counsel inv...,politicsNews,"December 31, 2017",1
3,FBI Russia probe helped by Australian diplomat...,WASHINGTON (Reuters) - Trump campaign adviser ...,politicsNews,"December 30, 2017",1
4,Trump wants Postal Service to charge 'much mor...,SEATTLE/WASHINGTON (Reuters) - President Donal...,politicsNews,"December 29, 2017",1

In [51]:
#Checking for Labeling
fake_data.head()

,title,text,subject,date,label
0,Donald Trump Sends Out Embarrassing New Year’...,Donald Trump just couldn t wish all Americans ...,News,"December 31, 2017",0
1,Drunk Bragging Trump Staffer Started Russian ...,House Intelligence Committee Chairman Devin Nu...,News,"December 31, 2017",0
2,Sheriff David Clarke Becomes An Internet Joke...,"On Friday, it was revealed that former Milwauk...",News,"December 30, 2017",0
3,Trump Is So Obsessed He Even Has Obama’s Name...,"On Christmas day, Donald Trump announced that ...",News,"December 29, 2017",0
4,Pope Francis Just Called Out Donald Trump Dur...,Pope Francis used his annual Christmas Day mes...,News,"December 25, 2017",0

### Combining the both true or fake dataset to feed into the model

In [52]:
# merge both data
news = pd.concat([true_data,fake_data] , axis = 0)

In [53]:
# checking for concating --- 1st 7 rows
news.head(7)

,title,text,subject,date,label
0,"As U.S. budget fight looms, Republicans flip t...",WASHINGTON (Reuters) - The head of a conservat...,politicsNews,"December 31, 2017",1
1,U.S. military to accept transgender recruits o...,WASHINGTON (Reuters) - Transgender people will...,politicsNews,"December 29, 2017",1
2,Senior U.S. Republican senator: 'Let Mr. Muell...,WASHINGTON (Reuters) - The special counsel inv...,politicsNews,"December 31, 2017",1
3,FBI Russia probe helped by Australian diplomat...,WASHINGTON (Reuters) - Trump campaign adviser ...,politicsNews,"December 30, 2017",1
4,Trump wants Postal Service to charge 'much mor...,SEATTLE/WASHINGTON (Reuters) - President Donal...,politicsNews,"December 29, 2017",1
5,"White House, Congress prepare for talks on spe...","WEST PALM BEACH, Fla./WASHINGTON (Reuters) - T...",politicsNews,"December 29, 2017",1
6,"Trump says Russia probe will be fair, but time...","WEST PALM BEACH, Fla (Reuters) - President Don...",politicsNews,"December 29, 2017",1

In [54]:
# checking the last 5 rows of the dataset
news.tail()

,title,text,subject,date,label
2382,WATCH: CNN Panelist HUMILIATES ‘Snowflake’ Tr...,Donald Trump is so thin-skinned that he would ...,News,"February 26, 2017",0
2383,"Trump Attacks The ‘Failing’ New York Times, B...",Donald Trump kicked off his Sunday morning by ...,News,"February 26, 2017",0
2384,Trump Goes On DELUSIONAL Tweet Storm About De...,Donald Trump has no reason to give a shit abou...,News,"February 26, 2017",0
2385,Muhammad Ali’s Son Detained At Airport Becaus...,Immigration officials in Florida proved how ou...,News,"February 25, 2017",0
2386,Trump Just Threw The WORST Insult YET Out To ...,"Donald Trump hates the press, unless the press...",News,"February 25, 2017",0

In [55]:
# Checking for Missing / Null values
news.isnull().sum()

title      0
text       0
subject    0
date       0
label      0
dtype: int64

## Removing the Irrevalent Features

In [56]:
#Feature selection
news = news.drop(['title' , 'subject' , 'date' ] , axis = 1)

In [57]:
#Checking the updated data
news.head()

                                                text  label
0  WASHINGTON (Reuters) - The head of a conservat...      1
1  WASHINGTON (Reuters) - Transgender people will...      1
2  WASHINGTON (Reuters) - The special counsel inv...      1
3  WASHINGTON (Reuters) - Trump campaign adviser ...      1
4  SEATTLE/WASHINGTON (Reuters) - President Donal...      1

#Reshuffling :
#### Because all the trues news are in first in the News file then all the fake news , need to reshuffl otherwise the  model result will be Baised

In [58]:
#Reshuffling
news = news.sample(frac=1)

In [59]:
#Checking for updation
news.head()

                                                   text  label
929   On Wednesday, the GOP   in an effort to deflec...      0
23    Alabama is a notoriously deep red state. It s ...      0
1229  Former FBI Director James Comey will testify b...      0
1226  On Thursday, thanks to strange Senate rules, J...      0
374   WASHINGTON (Reuters) - U.S. Secretary of State...      1

### Index Reset which become random due reshuffling

In [60]:
#Correcting the index
news = news.reset_index()

In [61]:
#Checking for the reset indexing
news.head()

   index                                               text  label
0    929  On Wednesday, the GOP   in an effort to deflec...      0
1     23  Alabama is a notoriously deep red state. It s ...      0
2   1229  Former FBI Director James Comey will testify b...      0
3   1226  On Thursday, thanks to strange Senate rules, J...      0
4    374  WASHINGTON (Reuters) - U.S. Secretary of State...      1

In [62]:
#Dropping the index that is inluded in the News file
news.drop(['index'] , axis = 1 , inplace = True)

In [63]:
# Checking the updated data
news.head()

                                                text  label
0  On Wednesday, the GOP   in an effort to deflec...      0
1  Alabama is a notoriously deep red state. It s ...      0
2  Former FBI Director James Comey will testify b...      0
3  On Thursday, thanks to strange Senate rules, J...      0
4  WASHINGTON (Reuters) - U.S. Secretary of State...      1

# Wordopt:
#### Removing the noise/not important  from the news column {"text"} so that modle can understand the only vital stuff

In [64]:
# importing the Regular Expression -- used for Data cleaning or manipulation of the data
import re

In [65]:
#Defining the function
def wordopt(text):
  #convert into lowercase
  text = text.lower()

  #remove punctution , URL
  text = re.sub(r'https?: //\S+|www\.\S+' , '' , text)
  #remove HTML Tags
  text = re.sub(r'<.*?>' , '' , text)
  #remove punctuation
  text = re.sub(r'[^\w\s]' , '' , text)
  #remove digits
  text = re.sub(r'\d' , '' , text)
  #remove newline characters
  text = re.sub(r'\n' , '' , text )
  return text

In [66]:
# applying it on the Text column in the News dataset to clean the data
news['text'] = news['text'].apply(wordopt)

In [67]:
#checking the updated data
news['text']

0       on wednesday the gop   in an effort to deflect...
1       alabama is a notoriously deep red state it s a...
2       former fbi director james comey will testify b...
3       on thursday thanks to strange senate rules joh...
4       washington reuters  us secretary of state rex ...
                              ...
5282    washington reuters  a coalition of  conservati...
5283    for more than  years donald trump has built hi...
5284    for months now the republicans have been doing...
5285    washington reuters  president donald trump sai...
5286    since taking the oath of office alleged presid...
Name: text, Length: 5287, dtype: object

#Splitting the dataset into
## 1: Features -- X independent Variable
## 2: Target -- y dependent Variable

In [68]:
#Splitting the data
X = news['text']
y = news['label']

In [69]:
#Checking the data
X

0       on wednesday the gop   in an effort to deflect...
1       alabama is a notoriously deep red state it s a...
2       former fbi director james comey will testify b...
3       on thursday thanks to strange senate rules joh...
4       washington reuters  us secretary of state rex ...
                              ...
5282    washington reuters  a coalition of  conservati...
5283    for more than  years donald trump has built hi...
5284    for months now the republicans have been doing...
5285    washington reuters  president donald trump sai...
5286    since taking the oath of office alleged presid...
Name: text, Length: 5287, dtype: object

In [70]:
#checking the data
y

0       0
1       0
2       0
3       0
4       1
       ..
5282    1
5283    0
5284    0
5285    1
5286    0
Name: label, Length: 5287, dtype: int64

## Splitting the data into Training or Testing data

In [71]:
#already Imported above
from sklearn.model_selection import train_test_split

In [72]:
#Splitting
X_train , X_test , y_train , y_test = train_test_split(X, y , test_size=0.3 , random_state=42)

In [73]:
#checking the shape -- no of rows and columns
X.shape

(5287,)

In [74]:
# shape
X_train.shape

(3700,)

In [75]:
# shape
X_test.shape

(1587,)

#Featture Extraction:
#### using Tfidfvectorizer -- to convert text data into numerical vector so that model can understand the data --- Tfidfvectorizer -- use on Text column in the News dataset

In [76]:
#Importing
from sklearn.feature_extraction.text import TfidfVectorizer

In [77]:
# creating variable and vectorzing the X_train or test
vectorization = TfidfVectorizer()
X_train_vec =  vectorization.fit_transform(X_train)
X_test_vec = vectorization.transform(X_test)

In [78]:
# checking for the update
X_train_vec

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 768244 stored elements and shape (3700, 46249)>

In [79]:
# checking for the update
X_test_vec

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 323468 stored elements and shape (1587, 46249)>

# Model Creation

In [80]:
#already imported above
from sklearn.linear_model import LogisticRegression

In [81]:
#creating Varible
LR_model = LogisticRegression()

# LR_model Training

In [82]:
LR_model.fit(X_train_vec , y_train)

LogisticRegression()

# LR_model Evalution

In [83]:
# Predicting
pred_LR = LR_model.predict(X_test_vec)

In [84]:
# analyzing the score of prediction
LR_model.score(X_test_vec , y_test)

0.9892879647132955

In [85]:
# already imported and printing the classification report
from sklearn.metrics import classification_report
print(classification_report(y_test , pred_LR))

              precision    recall  f1-score   support

           0       0.99      0.99      0.99       694
           1       0.99      0.99      0.99       893

    accuracy                           0.99      1587
   macro avg       0.99      0.99      0.99      1587
weighted avg       0.99      0.99      0.99      1587

# Decision Tree Classifier

# Model Creation

In [86]:
# Already imported
from sklearn.tree import DecisionTreeClassifier

In [87]:
# Intiating Variable
DTC_model = DecisionTreeClassifier()

# Training the DTC_model

In [88]:

DTC_model.fit(X_train_vec , y_train)

DecisionTreeClassifier()

# Evaluting the DTC_model

In [89]:
#predicting
pred_DTC = DTC_model.predict(X_test_vec)

In [90]:
# analzying the score
DTC_model.score(X_test_vec , y_test)

0.9974795211090107

In [91]:
# printing the classification report for DTC_model
print(classification_report(y_test , pred_DTC))

              precision    recall  f1-score   support

           0       1.00      0.99      1.00       694
           1       1.00      1.00      1.00       893

    accuracy                           1.00      1587
   macro avg       1.00      1.00      1.00      1587
weighted avg       1.00      1.00      1.00      1587

# Ensemble Technique--- Random Forest Classifier

# Model Creation

In [92]:
#already imported above
from sklearn.ensemble import RandomForestClassifier

In [93]:
RFC_model = RandomForestClassifier()

#Training the RFC_model

In [94]:
RFC_model.fit(X_train_vec , y_train)

RandomForestClassifier()

# Evakuting the RFC_model

In [95]:
#predicting
predict_RFC = RFC_model.predict(X_test_vec)

In [96]:
#analzing the score of the model
RFC_model.score(X_test_vec , y_test)

0.9930686830497795

In [97]:
#printing the classification report of RFC_model
print(classification_report(y_test,predict_RFC))

              precision    recall  f1-score   support

           0       0.99      0.99      0.99       694
           1       1.00      0.99      0.99       893

    accuracy                           0.99      1587
   macro avg       0.99      0.99      0.99      1587
weighted avg       0.99      0.99      0.99      1587

# Gradient Boosting Algorithm

# Model creation

In [98]:
# already imported above
from sklearn.ensemble import GradientBoostingClassifier

In [99]:
# Intiating the variable
GBC_model = GradientBoostingClassifier()

# Training the GBC_model

In [100]:
GBC_model.fit(X_train_vec , y_train)

GradientBoostingClassifier()

# Evaluting the GBC_model

In [101]:
#predicting
predict_GBC = GBC_model.predict(X_test_vec)

In [102]:
# analyzing the score
GBC_model.score(X_test_vec , y_test)

0.998109640831758

In [103]:
#printing the classification report
print(classification_report(y_test , predict_GBC))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00       694
           1       1.00      1.00      1.00       893

    accuracy                           1.00      1587
   macro avg       1.00      1.00      1.00      1587
weighted avg       1.00      1.00      1.00      1587

# Building the Predictive system

In [104]:
# Defining the output when a news prediction come
def output_label(n):
  if n == 0:
    return 'It is a Fake News'
  elif n ==1:
    return 'It is a Genuine News'

In [113]:
#defining the overall functionality that are describe above
def manual_testing(news):
  testing_news = {"text" : [news]}
  new_def_test = pd.DataFrame(testing_news)
  new_def_test["text"] = new_def_test["text"].apply(wordopt)
  new_X_test = new_def_test["text"]
  new_X_test_vec = vectorization.transform(new_X_test)
  pred_LR = LR_model.predict(new_X_test_vec)
  pred_DTC = DTC_model.predict(new_X_test_vec)
  pred_RFC = RFC_model.predict(new_X_test_vec)
  predict_GBC = GBC_model.predict(new_X_test_vec)
  return "\n\nLR Prediction: {} \n\nDTC Prediction: {} \n\nRFC Prediction: {} \n\nGBC Predicion : {}" . format(output_label(pred_LR[0]),
         output_label(pred_DTC[0]) , output_label(predict_RFC[0]), output_label(predict_GBC[0]))

In [127]:
#taking the input from user
news_article = str(input())

https://www.youtube.com/watch?v=WiCRTWkyKnI

In [128]:
#Predicting the news as genuine or fake by 4 models
manual_testing(news_article)

'\n\nLR Prediction: It is a Genuine News \n\nDTC Prediction: It is a Fake News \n\nRFC Prediction: It is a Genuine News \n\nGBC Predicion : It is a Fake News'