# Import dependencies

In [24]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

# Data Collection

In [25]:
cancer_dataset = pd.read_csv("/content/data.csv")

# Data Preprocessing

In [26]:
# printing the 1st five rows of dataset
cancer_dataset.head()

         id diagnosis  ...  fractal_dimension_worst  Unnamed: 32
0    842302         M  ...                  0.11890          NaN
1    842517         M  ...                  0.08902          NaN
2  84300903         M  ...                  0.08758          NaN
3  84348301         M  ...                  0.17300          NaN
4  84358402         M  ...                  0.07678          NaN

[5 rows x 33 columns]

In [27]:
# printing the last 5 rows of dataset
cancer_dataset.tail(10)

         id diagnosis  ...  fractal_dimension_worst  Unnamed: 32
559  925291         B  ...                  0.08732          NaN
560  925292         B  ...                  0.08321          NaN
561  925311         B  ...                  0.05905          NaN
562  925622         M  ...                  0.14090          NaN
563  926125         M  ...                  0.09873          NaN
564  926424         M  ...                  0.07115          NaN
565  926682         M  ...                  0.06637          NaN
566  926954         M  ...                  0.07820          NaN
567  927241         M  ...                  0.12400          NaN
568   92751         B  ...                  0.07039          NaN

[10 rows x 33 columns]

In [28]:
# finding the numbers of rows and columns in the dataset
cancer_dataset.shape

(569, 33)

In [29]:
# finding the information about the dataset
cancer_dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 569 entries, 0 to 568
Data columns (total 33 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   id                       569 non-null    int64
 1   diagnosis                569 non-null    object
 2   radius_mean              569 non-null    float64
 3   texture_mean             569 non-null    float64
 4   perimeter_mean           569 non-null    float64
 5   area_mean                569 non-null    float64
 6   smoothness_mean          569 non-null    float64
 7   compactness_mean         569 non-null    float64
 8   concavity_mean           569 non-null    float64
 9   concave points_mean      569 non-null    float64
 10  symmetry_mean            569 non-null    float64
 11  fractal_dimension_mean   569 non-null    float64
 12  radius_se                569 non-null    float64
 13  texture_se               569 non-null    float64
 14  perimeter_se             569 non-null    float64
 15  area_se                  569 non-null    float64
 16  smoothness_se            569 non-null    float64
 17  compactness_se           569 non-null    float64
 18  concavity_se             569 non-null    float64
 19  concave points_se        569 non-null    float64
 20  symmetry_se              569 non-null    float64
 21  fractal_dimension_se     569 non-null    float64
 22  radius_worst             569 non-null    float64
 23  texture_worst            569 non-null    float64
 24  perimeter_worst          569 non-null    float64
 25  area_worst               569 non-null    float64
 26  smoothness_worst         569 non-null    float64
 27  compactness_worst        569 non-null    float64
 28  concavity_worst          569 non-null    float64
 29  concave points_worst     569 non-null    float64
 30  symmetry_worst           569 non-null    float64
 31  fractal_dimension_worst  569 non-null    float64
 32  Unnamed: 32              0 non-null      float64
dtypes: float64(31), int64(1), object(1)
memory usage: 146.8+ KB

In [30]:
# finding the missing values
cancer_dataset.isnull().sum()

id                           0
diagnosis                    0
radius_mean                  0
texture_mean                 0
perimeter_mean               0
area_mean                    0
smoothness_mean              0
compactness_mean             0
concavity_mean               0
concave points_mean          0
symmetry_mean                0
fractal_dimension_mean       0
radius_se                    0
texture_se                   0
perimeter_se                 0
area_se                      0
smoothness_se                0
compactness_se               0
concavity_se                 0
concave points_se            0
symmetry_se                  0
fractal_dimension_se         0
radius_worst                 0
texture_worst                0
perimeter_worst              0
area_worst                   0
smoothness_worst             0
compactness_worst            0
concavity_worst              0
concave points_worst         0
symmetry_worst               0
fractal_dimension_worst      0
Unnamed: 32                569
dtype: int64

0 -- Benign or not cancerous
1 -- Malignant or cancerous

In [31]:
# Rename 'diagnosis' column to 'target' -- as this is the target column
cancer_dataset.rename(columns={'diagnosis': 'target'}, inplace=True)

# Map M -> 1 (malignant/cancerous), B -> 0 (benign/not cancerous)
cancer_dataset['target'] = cancer_dataset['target'].map({'M': 1, 'B': 0})

# Check the result
cancer_dataset.head()

         id  target  ...  fractal_dimension_worst  Unnamed: 32
0    842302       1  ...                  0.11890          NaN
1    842517       1  ...                  0.08902          NaN
2  84300903       1  ...                  0.08758          NaN
3  84348301       1  ...                  0.17300          NaN
4  84358402       1  ...                  0.07678          NaN

[5 rows x 33 columns]

In [32]:
# removing the column no 32 named as Unnamed:32 beacuse it contain Null values NAN
cancer_dataset.drop('Unnamed: 32', axis=1, inplace=True)

In [33]:
# Checking the updation
cancer_dataset.head()

         id  target  ...  symmetry_worst  fractal_dimension_worst
0    842302       1  ...          0.4601                  0.11890
1    842517       1  ...          0.2750                  0.08902
2  84300903       1  ...          0.3613                  0.08758
3  84348301       1  ...          0.6638                  0.17300
4  84358402       1  ...          0.2364                  0.07678

[5 rows x 32 columns]

In [34]:
# finding the Statistical meaures
cancer_dataset.describe()

                 id      target  ...  symmetry_worst  fractal_dimension_worst
count  5.690000e+02  569.000000  ...      569.000000               569.000000
mean   3.037183e+07    0.372583  ...        0.290076                 0.083946
std    1.250206e+08    0.483918  ...        0.061867                 0.018061
min    8.670000e+03    0.000000  ...        0.156500                 0.055040
25%    8.692180e+05    0.000000  ...        0.250400                 0.071460
50%    9.060240e+05    0.000000  ...        0.282200                 0.080040
75%    8.813129e+06    1.000000  ...        0.317900                 0.092080
max    9.113205e+08    1.000000  ...        0.663800                 0.207500

[8 rows x 32 columns]

In [35]:
# checking the distribution of the target variable --- Label column
# Finding how many of the data entries are Malignant or Begnin
cancer_dataset['target'].value_counts()

target
0    357
1    212
Name: count, dtype: int64

In [36]:
# finding the mean of the target column
cancer_dataset.groupby('target').mean()

                  id  radius_mean  ...  symmetry_worst  fractal_dimension_worst
target                             ...
0       2.654382e+07    12.146524  ...        0.270246                 0.079442
1       3.681805e+07    17.462830  ...        0.323468                 0.091530

[2 rows x 31 columns]

# Splitting the data into Features or Targets

In [38]:
#feature -- Independent Variable
X = cancer_dataset.drop(columns='target' , axis=1)

In [39]:
# target  -- Dependent Variable
y = cancer_dataset['target']

In [40]:
# Checking the updation
X

           id  radius_mean  ...  symmetry_worst  fractal_dimension_worst
0      842302        17.99  ...          0.4601                  0.11890
1      842517        20.57  ...          0.2750                  0.08902
2    84300903        19.69  ...          0.3613                  0.08758
3    84348301        11.42  ...          0.6638                  0.17300
4    84358402        20.29  ...          0.2364                  0.07678
..        ...          ...  ...             ...                      ...
564    926424        21.56  ...          0.2060                  0.07115
565    926682        20.13  ...          0.2572                  0.06637
566    926954        16.60  ...          0.2218                  0.07820
567    927241        20.60  ...          0.4087                  0.12400
568     92751         7.76  ...          0.2871                  0.07039

[569 rows x 31 columns]

In [41]:
# Checking the updation
y

0      1
1      1
2      1
3      1
4      1
      ..
564    1
565    1
566    1
567    1
568    0
Name: target, Length: 569, dtype: int64

# Splitting the data into Training data or Testing data

In [42]:
# Train_Test_Split
X_train , X_test , y_train , y_test = train_test_split(X, y , test_size = 0.3 , random_state = 42)

In [44]:
# finding the shape of X
X.shape

(569, 31)

In [45]:
# finding the shape of X_train
X_train.shape

(398, 31)

In [46]:
# finding the shape of X_test
X_test.shape

(171, 31)

# Model Creation

In [47]:
# Model Intialization
LR_model = LogisticRegression()

# Fitting the data to model

In [48]:
LR_model.fit(X_train , y_train)

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

# Model Evalution

#### Accuracy on Training Data

In [49]:
training_data_prediction = LR_model.predict(X_train)
training_data_accuracy = accuracy_score(y_train , training_data_prediction)
print("Accuracy on Training data : " , training_data_accuracy)

Accuracy on Training data :  0.8944723618090452

#### Accuracy on Testing Data

In [50]:
testing_data_prediction = LR_model.predict(X_test)
testing_data_accuracy = accuracy_score(y_test , testing_data_prediction)
print("Accuracy on Testing data : " , testing_data_accuracy)

Accuracy on Testing data :  0.9298245614035088

# Building a Predictive System

In [56]:
input_data = (910167,12.46,12.83,78.83,477.3,0.07372,0.04043,0.007173,0.01149,0.1613,0.06013,0.3276,1.486,2.108,24.6,0.01039,0.01003,0.006416,0.007895,0.02869,0.004821,13.19,16.36,83.24,534,0.09439,0.06477,0.01674,0.0268,0.228,0.07028)
# converting the input data into  numpy array
input_data_as_numpy_array = np.asarray(input_data)
# reshaping the input_data_as_numpy_array as we are predicting for one datapoint
input_data_reshaped = input_data_as_numpy_array.reshape(1,-1)


# make prediction
prediction = LR_model.predict(input_data_reshaped)
print(prediction)

if prediction[0] == 0:
  print('The Breast cancer is Benign')
else:
  print('The Breast Cancer is Malignant')

[0]
The Breast cancer is Benign

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(