# Importing Dependencies

In [3]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [1]:
import zipfile

with zipfile.ZipFile('/content/archive (1).zip', 'r') as zip_ref:
    zip_ref.extractall('/content/')

print('File extracted successfully!')

File extracted successfully!

# Importing CSV to Pandas

In [4]:
credit_card_dataset = pd.read_csv('/content/creditcard.csv')

# Visualize the Data

In [6]:
credit_card_dataset.head(15)

    Time        V1        V2        V3  ...       V27       V28  Amount  Class
0    0.0 -1.359807 -0.072781  2.536347  ...  0.133558 -0.021053  149.62      0
1    0.0  1.191857  0.266151  0.166480  ... -0.008983  0.014724    2.69      0
2    1.0 -1.358354 -1.340163  1.773209  ... -0.055353 -0.059752  378.66      0
3    1.0 -0.966272 -0.185226  1.792993  ...  0.062723  0.061458  123.50      0
4    2.0 -1.158233  0.877737  1.548718  ...  0.219422  0.215153   69.99      0
5    2.0 -0.425966  0.960523  1.141109  ...  0.253844  0.081080    3.67      0
6    4.0  1.229658  0.141004  0.045371  ...  0.034507  0.005168    4.99      0
7    7.0 -0.644269  1.417964  1.074380  ... -1.206921 -1.085339   40.80      0
8    7.0 -0.894286  0.286157 -0.113192  ...  0.011747  0.142404   93.20      0
9    9.0 -0.338262  1.119593  1.044367  ...  0.246219  0.083076    3.68      0
10  10.0  1.449044 -1.176339  0.913860  ...  0.042850  0.016253    7.80      0
11  10.0  0.384978  0.616109 -0.874300  ...  0.042472 -0.054337    9.99      0
12  10.0  1.249999 -1.221637  0.383930  ...  0.026416  0.042422  121.50      0
13  11.0  1.069374  0.287722  0.828613  ...  0.021491  0.021293   27.50      0
14  12.0 -2.791855 -0.327771  1.641750  ... -0.164778 -0.030154   58.80      0

[15 rows x 31 columns]

# Class -- 0 legal Transaction , -- 1 Fraudlent Trasaction

In [7]:
credit_card_dataset.tail()

            Time         V1         V2  ...       V28  Amount  Class
284802  172786.0 -11.881118  10.071785  ...  0.823731    0.77      0
284803  172787.0  -0.732789  -0.055080  ... -0.053527   24.79      0
284804  172788.0   1.919565  -0.301254  ... -0.026561   67.88      0
284805  172788.0  -0.240440   0.530483  ...  0.104533   10.00      0
284806  172792.0  -0.533413  -0.189733  ...  0.013649  217.00      0

[5 rows x 31 columns]

# Dataset Information

In [8]:
credit_card_dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 284807 entries, 0 to 284806
Data columns (total 31 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   Time    284807 non-null  float64
 1   V1      284807 non-null  float64
 2   V2      284807 non-null  float64
 3   V3      284807 non-null  float64
 4   V4      284807 non-null  float64
 5   V5      284807 non-null  float64
 6   V6      284807 non-null  float64
 7   V7      284807 non-null  float64
 8   V8      284807 non-null  float64
 9   V9      284807 non-null  float64
 10  V10     284807 non-null  float64
 11  V11     284807 non-null  float64
 12  V12     284807 non-null  float64
 13  V13     284807 non-null  float64
 14  V14     284807 non-null  float64
 15  V15     284807 non-null  float64
 16  V16     284807 non-null  float64
 17  V17     284807 non-null  float64
 18  V18     284807 non-null  float64
 19  V19     284807 non-null  float64
 20  V20     284807 non-null  float64
 21  V21     284807 non-null  float64
 22  V22     284807 non-null  float64
 23  V23     284807 non-null  float64
 24  V24     284807 non-null  float64
 25  V25     284807 non-null  float64
 26  V26     284807 non-null  float64
 27  V27     284807 non-null  float64
 28  V28     284807 non-null  float64
 29  Amount  284807 non-null  float64
 30  Class   284807 non-null  int64
dtypes: float64(30), int64(1)
memory usage: 67.4 MB

In [9]:
credit_card_dataset.isnull().sum()

Time      0
V1        0
V2        0
V3        0
V4        0
V5        0
V6        0
V7        0
V8        0
V9        0
V10       0
V11       0
V12       0
V13       0
V14       0
V15       0
V16       0
V17       0
V18       0
V19       0
V20       0
V21       0
V22       0
V23       0
V24       0
V25       0
V26       0
V27       0
V28       0
Amount    0
Class     0
dtype: int64

In [10]:
#Distribution of legit and fradulent transaction
credit_card_dataset['Class'].value_counts()

Class
0    284315
1       492
Name: count, dtype: int64

Highly Unbalanced Datasets

In [11]:
# Separating the data for analysis
legit = credit_card_dataset[credit_card_dataset.Class == 0]
fraud = credit_card_dataset[credit_card_dataset.Class == 1]

In [12]:
print(legit.shape)
print(fraud.shape)

(284315, 31)
(492, 31)

# Statistical meausres for the data

In [13]:
legit.Amount.describe()

count    284315.000000
mean         88.291022
std         250.105092
min           0.000000
25%           5.650000
50%          22.000000
75%          77.050000
max       25691.160000
Name: Amount, dtype: float64

In [14]:
fraud.Amount.describe()

count     492.000000
mean      122.211321
std       256.683288
min         0.000000
25%         1.000000
50%         9.250000
75%       105.890000
max      2125.870000
Name: Amount, dtype: float64

In [16]:
# comapre the values of legit and Fraud transaction
credit_card_dataset.groupby('Class').mean()

               Time        V1        V2  ...       V27       V28      Amount
Class                                    ...
0      94838.202258  0.008258 -0.006271  ... -0.000295 -0.000131   88.291022
1      80746.806911 -4.771948  3.623778  ...  0.170575  0.075667  122.211321

[2 rows x 30 columns]

# Under- Sampling

# Build a sample dataset containing similiar distribution of normal Transacion and Fradulent Tansaction

# number  of F.T is 492

In [17]:
legit_sample  = legit.sample(n=492 )

# Concatenating 2 datasets , Fradulent + legit_ sample

In [19]:
new_dataset = pd.concat([legit_sample , fraud ] , axis = 0)

In [22]:
new_dataset.head(5)

            Time        V1        V2  ...       V28  Amount  Class
220563  142222.0 -0.919328  0.863307  ...  0.114022   15.09      0
91225    63365.0 -1.035231  0.393270  ... -0.644559  815.20      0
97040    66049.0  1.023708 -0.291587  ...  0.017610  161.90      0
226366  144599.0 -0.822427  1.519836  ...  0.051656    0.00      0
196907  131751.0  0.170976  0.940984  ... -0.066387   54.54      0

[5 rows x 31 columns]

In [23]:
new_dataset.tail()

            Time        V1        V2  ...       V28  Amount  Class
279863  169142.0 -1.927883  1.125653  ...  0.147968  390.00      1
280143  169347.0  1.378559  1.289381  ...  0.186637    0.76      1
280149  169351.0 -0.676143  1.126366  ...  0.194361   77.89      1
281144  169966.0 -3.113832  0.585864  ... -0.253700  245.00      1
281674  170348.0  1.991976  0.158476  ... -0.015309   42.53      1

[5 rows x 31 columns]

In [24]:
new_dataset['Class'].value_counts()

Class
0    492
1    492
Name: count, dtype: int64

In [25]:
new_dataset.groupby('Class').mean()

               Time        V1        V2  ...       V27       V28      Amount
Class                                    ...
0      96841.510163 -0.086965  0.082120  ... -0.021939  0.015468   86.917053
1      80746.806911 -4.771948  3.623778  ...  0.170575  0.075667  122.211321

[2 rows x 30 columns]

# split the data into Features and Tragets
features -- X  
Targets -- Y

In [26]:
X = new_dataset.drop(columns= 'Class' , axis = 1)
y = new_dataset['Class']

In [27]:
print(X)

            Time        V1        V2  ...       V27       V28  Amount
220563  142222.0 -0.919328  0.863307  ...  0.283474  0.114022   15.09
91225    63365.0 -1.035231  0.393270  ... -0.052380 -0.644559  815.20
97040    66049.0  1.023708 -0.291587  ... -0.143930  0.017610  161.90
226366  144599.0 -0.822427  1.519836  ... -0.013624  0.051656    0.00
196907  131751.0  0.170976  0.940984  ... -0.086846 -0.066387   54.54
...          ...       ...       ...  ...       ...       ...     ...
279863  169142.0 -1.927883  1.125653  ...  0.292680  0.147968  390.00
280143  169347.0  1.378559  1.289381  ...  0.389152  0.186637    0.76
280149  169351.0 -0.676143  1.126366  ...  0.385107  0.194361   77.89
281144  169966.0 -3.113832  0.585864  ...  0.884876 -0.253700  245.00
281674  170348.0  1.991976  0.158476  ...  0.002988 -0.015309   42.53

[984 rows x 30 columns]

In [28]:
print(y)

220563    0
91225     0
97040     0
226366    0
196907    0
         ..
279863    1
280143    1
280149    1
281144    1
281674    1
Name: Class, Length: 984, dtype: int64

# Split the data into training and testing data

In [32]:
X_train , X_test , y_train , y_test = train_test_split(X,y, stratify=y ,test_size = 0.2 , random_state = 42)

In [33]:
print(X.shape , X_train.shape , X_test.shape)

(984, 30) (787, 30) (197, 30)

# Model Training

In [34]:
model = LogisticRegression()

# Training the model with training data

In [35]:
model.fit(X_train , y_train)

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

# Evalution of Model based on Accuracy Score

# 1st perform on Training data

In [36]:
X_train_prediction = model.predict(X_train)
training_data_accuracy = accuracy_score(X_train_prediction , y_train)

In [37]:
print('Accuracy on Training data : ' , training_data_accuracy)

Accuracy on Training data :  0.9466327827191868

# Accuracy on Test Data

In [40]:
X_test_prediction = model.predict(X_test)
test_data_accuracy = accuracy_score(X_test_prediction , y_test )
print('Accuracy on Test data :'  , test_data_accuracy)

Accuracy on Test data : 0.9644670050761421